services:
  - type: web
    name: my-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"  # Skip download if already installed manually
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"  # Ensure this path exists

