services:
  - type: web
    name: my-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true" # Skips Chromium download if you're installing manually
